### ISSUE TITLE
Investigate support for IPv6 in the web server

### ISSUE THREAD

**Issue by jurex** [encounterplus/encounterplus#171]

**Comment by rrgeorge** [comment]
I’m interested as to why this doesn’t work. It appears like the server isn’t even listening on the ipv6 address.
Also, possibly somewhat related, if there is no WiFi connection the IP is reported as “Unknown”. I suspect this is because you’re restricting the service to the WiFi interface (as you should). It may be better to have a message stating that it’s unavailable without a WiFi connection rather than using “Unknown” as the address.

**Comment by jurex** [comment]
> It appears like the server isn’t even listening on the ipv6 address
This and a couple of other small things. Got it fixed already, and I'm going to provide a switch to enable IPv6 if necessary
> It may be better to have a message stating that it’s unavailable without a WiFi connection rather than using “Unknown” as the address.
this will be handled differently in next version

<img width="245" alt="Screenshot 2020-06-01 at 13 59 26" src="https://user-images.githubusercontent.com/925257/83407182-7524cf00-a410-11ea-983e-a8f26510acb2.png">
