### ISSUE TITLE
Additive encounters improvement.

### ISSUE THREAD

**Issue by MrWickedClown** [encounterplus/encounterplus#282]
I know it's intentional that when you load an encounter when another is already loaded and on turn 0 that it gets replaced. But I continue to see people use a workflow where they load all monsters in a dungeon into one encounter to avoid this. I think people are assuming it always replaces the old encounter. 

I recommend since we have a clear encounter option that loading encounters should should always be additive rather than replace regardless of the turn number.

**Comment by Duseylicious** [comment]
I wouldn't mind when loading an encounter, if anything that would be removed via "reset encounter" is there, getting a pop up that asks "replace encounter?" or "Add to encounter?" Just a thought.  It's annoying when I accidentally add an encounter while still in initiative.  Then I have to reset the encounter and re-add the new encounter again.  

(I do this often because it's very easy to not noticed that I'm in initiative.  this ticket would help with that. https://github.com/encounterplus/encounterplus/issues/246 )

There could also be a preference option for this behavior "ask every time" "Always reset" "Always add"

**Comment by jurex** [comment]
need to decide how reset would behave with the new token workflow...

**Comment by jurex** [comment]
I agree with @MrWickedClown, load encounter should always add new creatures. There will be new load mode option modifier which could complicate things, so I wanna make it simple (to understand). There will be also group action menus which can be used to remove multiple tokens from combat at once. We can return to this later if necessary @Duseylicious
