### ISSUE TITLE
Better workflow for multiple parallel campaigns

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/encounterplus#36]
Going to open this as a placeholder for conversation and notes from Discord (and on here):

Several of us have multiple game son the go, and need a better way to manage them. Currently there is one game object even with multiple map tabs.

If instead everything could be connected to the campaign instead this would allow switching maps / campaigns, and having it auto-populate the party, monsters (ie, remember state per-campaign). As it's easy to create a new campaign with the same modules as another campaign this would still allow running the same maps in parallel with different players.

Would Shortcuts be global, or per campaign - potentially if it's a shortcut within the campaign then that would be stored per, but anything in the main library should probably be global.

This leads to an additional data point in the Library to see shortcuts stored in each campaign - and potentially allow them to be saved / loaded from the modules so distributing a module would allow it to also include useful shortcuts etc.

**Comment by maxlds** [comment]
It'd be nice to load up a Campaign and show ONLY the maps, shortcuts, etc that I've set up for that campaign. Right now, the main view gets cluttered and disorganized as I try to keep various campaigns' content up (i.e. shows all 3+ maps I have for each campaign). For example, I also have to get rid of current encounter information (how many hit points my players currently have), keep track of shortcuts, etc.  Heck, I'd even like to have my external screen settings (background image, default theme title, etc) specific to each campaign

**Comment by Tixuoty66** [comment]
From Shidara : One of my biggest frustrations with E+ is managing multiple campaigns simultaneously. I have two campaigns currently running—a Tuesday night campaign and a Sunday night campaign. Between each session, I have to essentially completely reset E+ to set up for the other campaign.  As it is, if I have to stop in the middle of an encounter or other precise moment, I have to take a screen shot and take manual notes about everything so that I can resume the game correctly after the next campaign runs. I would love for there to be a way to "save campaign" for E+ so I can save & reload the exact state of the game—open maps, party members & locations, monsters, everything.  I haven't seen any way to do that currently.

**Comment by jasontromney** [comment]
I'm running three different campaigns on EncounterPlus and this functionality would be very valuable!

**Comment by Tixuoty66** [comment]
> I'm running three different campaigns on EncounterPlus and this functionality would be very valuable!

Since release 4.11, it's much more easily to do that if your campaign is created as a "module". Then you create your 3 campaigns directory. When preparing or playing a session and loading a map from the module, you choose "Copy & Load" which will copy the map to the Campaign you want to. As tokens are now saved with maps, your maps will be saved with tokens at their last position, their current health... and so on. So if you stop a session in the middle of an encounter, you'll just have to load the map for your next game session to find your map with the tokens at their position, their current health points, etc... it keeps track of exactly where you stopped.

**Comment by jasontromney** [comment]
thanks for the tip. There are a few steps you missed though. I've been playing around with what you described and to make this work, you have to remove all monster and player tokens from combat first, then close the map. At that point when you open the map back up, everything is there, including the current hit points. Then you just add all of them back into combat. However, the initiative values are gone. This requires re-rolling initiative or manually entering them back in from notes. So, not quite what I'm looking for yet, but it's very close!

**Comment by jurex** [comment]
done
