### ISSUE TITLE
Sort order of module elements random without sort attribute

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#364]
When importing a module with elements that dont have the sort attribute set, the expected result should be either alphabetical or the order in the module.xml; but they appear in random order instead.

**Comment by jacobjohnston** [comment]
I think items without an order property should all have an implicitly high order (e.g. Int.Max or something) and then go alphabetical by title (as opposed to slug or XML order). Title should also be a tie breaker for elements with the same order.

**Comment by jurex** [comment]
content retrieval and sorting by `rank` in module/campaign is already too complex, I don't want to complicate it even further with additional sort field/fallback. I will revisit this again during upcoming module content overhaul.

**Comment by jurex** [comment]
damn, the sorting should fallback into creation time when rank fields are the same. Looks like something changed in the realm implementation, because it's not working at all in the current version. All my old modules are randomly sorted, and I'm pretty sure they were fine before. Sigh, looks like I cannot dodge this one with a weak `too complicated` excuse now 🙄

**Comment by jurex** [comment]
so, now I'm ordering first by `created` date  and then by `rank` field, it is enough to bring the original structure specified in the xml. I can revisit and implement more sophisticated solution later when working on module content overhaul if necessary. Closing for now
