### ISSUE TITLE
Feature Request: Add support for iframes in pages

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/encounterplus#457]
Add support for inserting iframes in pages. Currently, if you add an iframe to a page, loading the page will cause the device to open the iframe src in Safari.

**Comment by jurex** [comment]
So I've updated URL handler to allow iframe requests, but seems like the actual network request is blocked on iOS level. It's probably because of wkwebview `loadFileURL` sandboxing. Can't do much about it right now. Sorry. One way around could be support for remote URLs in the marker reference field, but that's a different beast.
