### ISSUE TITLE
Can't get to "Submit" button when loading new map art.

### ISSUE THREAD

**Issue by Taliesin1** [encounterplus/encounterplus#512]
### What went wrong?
Whenever I try to reload map art on an existing map, the finder window that comes up is not contained by my MacOS viewport, so I can't see the "Enter" button, or whatever it's labeled — like half the window is off-screen. I can still load the art by using the Return key on my keyboard, but the modal shouldn’t be getting cut off like that.

### What were you expecting to happen?
The window should be contained within the viewport, and the "Enter" or "Select" button visible. You can't even move or resize the window to get to the button.

### What steps can we follow to reproduce the issue?
1. Load an existing map
2. Try to replace the map art by using the Browse function

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): EncounterPlus 4.11.1
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): MacOS Big Sur 11.3.1 running on a MacBook Pro (16" 2019 with Retina Display)

### Any screenshots, videos, logs, or error messages?
<img width="1792" alt="Screen Shot 2021-05-12 at 8 05 47 PM" src="https://user-images.githubusercontent.com/10515719/118063179-2a207500-b35e-11eb-9f79-e30e14f4a592.png">

### Any other comments?
-

**Comment by jurex** [comment]
The document browser window is managed entirely by macOS, so I **cannot** really do anything about it.  It's weird that you can resize it but not move up. Maybe it will be fixed in the future macOS version, but until then, you can workaround the issue by making the whole E+ window smaller ( which will move the browser up), and than you can resize the document browser by dragging bottom right corner. MacOS will remember the new size so next time all buttons should be visible even with large E+ window. Thanks for bringing this up. Closing now.

**Comment by Taliesin1** [comment]
Okay, thanks!
