### ISSUE TITLE
Load Mode Overridden Bug

### ISSUE THREAD

**Issue by DHCross** [encounterplus/encounterplus#720]
### What went wrong?
- 

I choose my Load Mode in the settings to be "combat only".
Then I choose "insert creature" from combat menu. The creature inserted loaded into map as well as into combat tracker. This is not the behavior expected, as it ignores my chosen load mode.

However, if I insert creature using the main campaigner menu window options, then it adheres to my universal setting for Load Mode. So all is well in this scenario. I do like the long-press to choose load mode on the fly, and when done from the campaign window it works fine. 

### What were you expecting to happen?
- 

I expect inserted creatures to follow chosen Lode Mode regardless of which menu it is initiated from. 

### What steps can we follow to reproduce the issue?
1. 

See this video: https://cdn.discordapp.com/attachments/634387773872275466/986866227706220564/Unexpected.mov

### What software versions are you currently using?
- EncounterPlus (e.g. 4.11.1): 
- Operating System (e.g. "iOS/iPadOS 14.2" or "macOS 11.3"): 

4.15.3 (2808)

Ios 15.6

### Any screenshots, videos, logs, or error messages?

See this video: https://cdn.discordapp.com/attachments/634387773872275466/986866227706220564/Unexpected.mov

### Any other comments?
-

**Comment by jurex** [comment]
There is a special override when adding creatures using ... dots menu in the initiative window. It always load creatures using  "combat & map" mode, regardless of settings. It's like this because it was confusing for some new users, when the load mode was map only. 

I've changed the behaviour slightly, so when the load mode in the settings is "combat", app will insert creatures only to the combat (as expected), but when it's "map" or "combat and map", app will also insert into combat (just because using ... combat context menu).

**Comment by DHCross** [comment]
This makes sense, and I can understand the benefit to new users. Has
anybody been working on an updated full documentation for all of the
nuances of this very feature-rich app?
